version: 0.2

env:
  secrets-manager:
    DOCKERHUB_PASS: "/dockerhub/credentials:password"
    DOCKERHUB_USERNAME: "/dockerhub/credentials:username"
    
phases: 
  pre_build: # commands to be run before build
    commands:
    - echo Logging in to Amazon ECR....
    - aws --version
    - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
    - eval $(aws ecr get-login --region eu-central-1 --no-include-email | sed 's|https://||')
    - REPOSITORY_URI=200424512596.dkr.ecr.eu-central-1.amazonaws.com/aitec_racer
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:   
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t aitecmz/dcbaseimage2:latest -f Dockerfile-DCBaseImage2 .
    - docker tag aitecmz/dcbaseimage2:latest aitecmz/dcbaseimage2:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push aitecmz/dcbaseimage2:latest
      - docker push aitecmz/dcbaseimage2:$IMAGE_TAG  
  

