version: '3.4'
services:
    donkey:      
        image: aitecmz/donkeycar
        build:
            context: .
            dockerfile: Dockerfile
            network: host
        privileged: true
        ipc: host
        network_mode: "host"
        stdin_open: true
        devices:
            - /dev/video0:/dev/video0
            - /dev/input/js0:/dev/input/js0
        tty: true
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - /tmp/camsock:/tmp/camsock:rw
            - /tmp/argus_socket:/tmp/argus_socket:rw
            - /tmp/nvscsock:/tmp/nvscsock:rw
            - /sys:/sys
            - /var/local/projects/donkeycar:/:var/local/projects/donkeycar
        environment:
            TERM: xterm-256color
            DISPLAY: $DISPLAY
            NVIDIA_DRIVER_CAPABILITIE NVIDIA_VISIBLE_DEVICES: all
            NVIDIA_DRIVER_CAPABILITIES: compute,video,utility
            LD_PRELOAD: /usr/lib/aarch64-linux-gnu/libgomp.so.1
