From aitecmz/donkeycarbaseimage-v01

# Install apt-get packages
RUN apt-get update && apt-get install python3-docopt

# Install pip package
RUN pip3 install -U imgaug
 
# Install donkey
COPY ./donkeycar /var/local/projects/donkeycar
RUN cd /var/local/projects/donkeycar && \
       git checkout master \
       && pip install -e .[nano]

CMD ["python3", "/home/zamy/mycar/train.py", "/home/zamy/mycar/data/tub_1_09-04-21"]
