FROM ubuntu:18.04

# First install some packages with apt-get
RUN  apt-get update -y && apt-get install -y \
            libgstreamer1.0-0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly \
            gstreamer1.0-libav \
            gstreamer1.0-doc \
            gstreamer1.0-tools \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev
RUN  apt-get update -y && apt-get install -y  pkg-config \
 zlib1g-dev  libwebp-dev \
 libtbb2 libtbb-dev  \
 libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev libv4l-dev \
 libhdf5-serial-dev hdf5-tools libhdf5-dev zip libjpeg8-dev liblapack-dev libblas-dev gfortran \
 cmake
RUN apt-get install -y python3-dev python3-pip
RUN apt-get install -y libxslt1-dev libxml2-dev libffi-dev libcurl4-openssl-dev libssl-dev libpng-dev libopenblas-dev
RUN apt-get install -y libjpeg-dev zlib1g-dev libpython3-dev libavcodec-dev libavformat-dev libswscale-dev
RUN apt-get install -y openmpi-doc openmpi-bin libopenmpi-dev
RUN apt-get install -y autoconf autotools-dev build-essential gcc git
#Next, you will need to install packages with pip
RUN pip3 install -U pip testresources setuptools
RUN pip3 install -U futures protobuf pybind11
RUN pip3 install -U cython numpy future mock h5py==2.10.0
RUN pip3 install -U keras_preprocessing keras_applications gast
RUN pip3 install -U grpcio absl-py py-cpuinfo psutil portpicker six requests astor
RUN pip3 install -U termcolor wrapt google-pasta scipy pandas gdown

# This will install tensorflow and opencv 
RUN pip3 install --pre --extra-index-url https://developer.download.nvidia.com/compute/redist/jp/v44 tensorflow==2.2.0+nv20.6
RUN pip3 install -U torchvision opencv-python imgaug

