FROM ubuntu

#Prevent Docker-Engine restart during apt-get upgrade
#RUN echo '* libraries/restart-without-asking boolean true' | sudo debconf-set-selections

# First install some packages with apt-get
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y \
            libgstreamer1.0-0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly \
            gstreamer1.0-libav \
            gstreamer1.0-doc \
            gstreamer1.0-tools \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev
RUN apt-get install -y libhdf5-serial-dev hdf5-tools libhdf5-dev zlib1g-dev zip libjpeg8-dev liblapack-dev libblas-dev gfortran
RUN apt-get install -y python3-dev python3-pip pkg-config 
RUN apt-get install -y libxslt1-dev libxml2-dev libffi-dev libcurl4-openssl-dev libssl-dev libpng-dev libopenblas-dev
RUN apt-get install -y git
RUN apt-get install -y openmpi-doc openmpi-bin libopenmpi-dev

#RUN apt-get install -y libwebp-dev libtbb2 libtbb-dev  libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev libv4l-dev cmake
#RUN apt-get install -y autoconf autotools-dev build-essential gcc 

#Next, you will need to install packages with pip
RUN pip3 install -U pip testresources setuptools
RUN pip3 install -U futures protobuf pybind11
RUN pip3 install -U cython numpy future mock h5py==2.10.0  
RUN pip3 install -U keras_preprocessing keras_applications gast
RUN pip3 install -U grpcio absl-py py-cpuinfo psutil portpicker six requests astor 
RUN pip3 install -U termcolor wrapt google-pasta scipy pandas gdown

# Install Tensorflow as system package
RUN pip3 install --pre --extra-index-url https://developer.download.nvidia.com/compute/redist/jp/v44 tensorflow==2.2.0+nv20.6

########################################
# Install PyTorch v1.7 - torchvision v0.8.1
# pytorch 1.6.0-rc2
# https://forums.developer.nvidia.com/t/pytorch-for-jetson-nano-version-1-5-0-now-available/72048/392
RUN wget https://nvidia.box.com/shared/static/wa34qwrwtk9njtyarwt5nvo6imenfy26.whl -O torch-1.7.0-cp36-cp36m-linux_aarch64.whl && pip3 install ./torch-1.7.0-cp36-cp36m-linux_aarch64.whl

# Install PyTorch Vision
RUN apt-get install libjpeg-dev zlib1g-dev libpython3-dev libavcodec-dev libavformat-dev libswscale-dev
RUN mkdir -p ~/projects && cd ~/projects
RUN git clone --branch v0.8.1 https://github.com/pytorch/vision torchvision && cd torchvision && export BUILD_VERSION=0.8.1 && python3 setup.py install