---
# travis pipeline
dist: focal

os:
  - linux
  - osx

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    sudo apt-get update -qq;
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --append channels conda-forge
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then conda env create -f install/envs/mac.yml ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then conda env create -f install/envs/ubuntu.yml ; fi
  - conda activate donkey
  - pip install -e .
  - conda env export > environment.yml
  - cat environment.yml

script:
  - pytest -v donkeycar/tests --cov=./

stages:
  - name: docs
  - name: lint
  - name: deploy
    if: branch = master

jobs:
  fast_finish: false
  allow_failures:
    - name: markdownlint
    - name: yamllint
    - name: black

  include:

    # mkdocs
    - stage: docs
      name: mkdocs
      language: python
      install:
        - pip install mkdocs
      script:
        - mkdocs build

    # black - The uncompromising Python code formatter - https://github.com/psf/black
    # it requires python 3.6
    - stage: lint
      name: black
      language: python
      install:
        - pip install --upgrade pip
        - hash -r
        - pip install black
      script:
        - "black --check ."

    # yamllint https://github.com/adrienverge/yamllint
    - stage: lint
      name: yamllint
      language: shell
      install: skip
      script:
        - "docker run --rm -v $PWD:/yaml:ro sdesbure/yamllint yamllint ."

    # markdownlint CLI https://github.com/06kellyjac/docker_markdownlint-cli
    - stage: lint
      name: markdownlint
      language: shell
      install: skip
      script:
        - "docker run -v $PWD:/markdown:ro 06kellyjac/markdownlint-cli ."

    - stage: deploy
      python: 3.6
      script: skip
      deploy:
        provider: pypi
        username: wroscoe
        password:
          # yamllint disable-line rule:line-length
          secure: Y64NS2etlOIjKMTLQex+5H/QrKdBzwGjhZ9VVp1NXyx76oqg0ygn5lOPcMAvQbuJbGzT0E/5q/EDhJAh6YjyjVYAS2UgBUehpY5Nu0oYFTfWCTC9fbQRn0XRLXPeZR3BKZ1cAxDCMm4a6iZ4M8CqatN73IexcORCYgkIXZfGRVGcAdLonWzkXPqIwe287e7TiQAx6wM6e7k4DRRUFcrw56lLWTG6FEkauQDNXJFlySwesIgFni+K59tHcxP1U00NTV5utTaNzkkFwro4bp6EsVHEYr8Hgz2Sv0mxAggWmXaMGwILahTSVoRznFsik4r3DiOwVEAc+aeTHg9NJin5/ic4ShODMPKkBQInUNxgmE8cZy5EpZ+a9Xbp1dNt/+x56Bmz+bKoQq/e0ydIBNXCeaT41VFyJTjz9db01HwUPZHfp0NCyIo5QcknH98G0oLmaqv43qGJzmaQi0h4BkkmgI5HpkE12MSDC8QFsDKmOXlj/I4WEWXuPslhuKTgYNadFGdTkfbhnbMjRDkuNfL8YSXwnNDTcB5qT3hIYWGVKN2qAAljWniWHdQMMosMv7CwfoM7IO6apgBuvoMJOMunHEgyGDX5Hb1Y5YYa+OC/0eCfcIEScoPM0JHtMmznYlIv5vwx8B3yK0qk0W8nIv65bZvP5eYBF1zLgeE2FLsuc1o=
        on:  # yamllint disable-line rule:truthy
          tags: true

after_success:
  - codecov
